FlappyGame/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gameApp.urls'))
]

gameApp/urls.py
from django.urls import path
from . import views

app_name = "gameApp"

urlpatterns = [
    path('', views.index, name='index'),
    path('game', views.game, name='game'),
    path('home', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('signup', views.signup, name='signup'),
]

gameApp/models.py
from django.db import models

# Create your models here.

gameApp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from boto3.dynamodb.conditions import Key
import boto3

def index(request):
	return render(request, 'gameApp/index.html', )

def game(request):
	return render(request, 'gameApp/game.html', )

def login(request):
    if request.method == 'POST':
        s3 = boto3.resource('s3')
        bucket = s3.Bucket('user-image-flappyyou')
        dynamodb_client = boto3.client('dynamodb')
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username)

        if user_exists(username, dynamodb_client, password):
            with open('image', 'wb') as data:
                bucket.download_fileobj(username, data)
                print(data)

            return HttpResponseRedirect('/home')
        else:
            context = {
                "error" : "Error - Please Sign up"
            }
            return render(request, 'gameApp/login.html', context)
    else:
        return render(request, 'gameApp/login.html', {})

def signup(request):
    print("im here")
    print(request.method)

    if request.method == 'POST':
        s3 = boto3.resource('s3')
        bucket = s3.Bucket('user-image-flappyyou')
        dynamodb_client = boto3.client('dynamodb')
        username = request.POST.get('username')
        email = request.POST.get('email')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        password = request.POST.get('password')
        image = request.FILES['filename']

        print(image)

        if user_exists(username, dynamodb_client):
            context = {
                "error" : "Error - User exists"
            }
            return render(request, 'gameApp/signup.html', context)

        else:

            # Create user


            # Fields are case sensitive
            item = {
                'Username': {'S': username},
                'Email': {'S': email},
                'FirstName': {'S': firstname},
                'LastName': {'S': lastname},
                'Password': {'S': password}
            }

            response = dynamodb_client.put_item(
                TableName='Users', 
                Item=item
            )

            bucket.upload_fileobj(image, username)

            print(response)

            context = {
                "error" : "User created !!"
            }

            return render(request, 'gameApp/index.html', context)


    return render(request, 'gameApp/signup.html', )

#if password value not provided, it will be initialized as none.
def  user_exists(username, dynamodb_client, password=None):
    response = dynamodb_client.get_item(
        TableName='Users',
        Key={
            'Username': {'S': username}
        }
    )

    # Empty dictionaries are false in python
    if response.get("Item"):
        if password:
            return response.get("Item").get("Password").get("S") == password
        return True
    else:
        return False 

# Create your views here.

gameApp/templates/gameApp/game.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<style>
			canvas { 
				border:1px solid #d3d3d3;
				background-image: url('{% static 'gameApp/img/background.png' %}');
				background-repeat: no-repeat;
				background-size: cover;
				background-position: absolute;
				top: 0px;
				left: 0px;
				right: 0px;
				bottom: 0px;
				margin: auto;
			}
		</style>
		<script src="{% static 'gameApp/js/game.js' %}" type="text/javascript">
			
		</script>
	</head>
	<body onload="startGame()">
	</body>
</html>

gameApp/templates/gameApp/index.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Flappy You</title>
        <link rel="icon" type="image/x-icon" href="{% static 'gameApp/img/bird.png' %}" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	</head>
		<style>
			body{
				background-image: url('{% static 'gameApp/img/bg.jpg' %}');
				background-repeat: no-repeat;
				background-size: cover;
				background-position: absolute;
				top: 0px;
				left: 0px;
				right: 0px;
				bottom: 0px;
				margin: auto;
			}
		</style>
		<center>
			<a href="game">
				<button type="button" class="btn btn-dark">PLAY NOW</button>
			</a>
			<a href="login">
				<button type="button" class="btn btn-dark">LOG IN</button>
			</a>
		</center>
		<style type="">
			button{
				background-color: #EFFF2B;
				border: none;
				color: black;
				padding: 15px 32px;
				text-align: center;
				text-decoration: none;
				display: inline-block;
				font-size: 16px;
				margin: 4px 2px;
				cursor: pointer;
			}			
		</style>
</html> 

gameApp/templates/gameApp/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>FLAPPY YOU</title>
<link rel="icon" type="image/x-icon" href="{% static 'gameApp/img/bird.png' %}" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
    body{
        background-image: url('{% static 'gameApp/img/login.png' %}');
        background-repeat: no-repeat;
        background-size: cover;
        background-position: absolute;
        top: 0px;
        left: 0px;
        right: 0px;
        bottom: 0px;
        margin: auto;
            }
</style>

<style>
    .login-form {
        width: 340px;
        margin: 50px auto;
        font-size: 15px;
    }
    .login-form form {
        margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }

</style>
</head>
<body>
<div class="login-form">
    <form action="{% url 'gameApp:login' %}" method="post">
        {% csrf_token %}
        <h2>{{error}}</h2>
        <h2 class="text-center">Log in</h2>       
        <div class="form-group">
            <input type="text" class="form-control" name="username" placeholder="Username" required="required">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" name="password" placeholder="Password" required="required">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
        </div>       
    </form>
    <p class="text-center"><a href="/signup">Create an Account</a></p>
</div>
</body>
</html>

gameApp/templates/gameApp/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>FLAPPY YOU</title>
<link rel="icon" type="image/x-icon" href="{% static 'gameApp/img/bird.png' %}" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

<style>
	body {
		color: #999;
		background: #f5f5f5;
		font-family: 'Roboto', sans-serif;
		background-image: url('{% static 'gameApp/img/login.png' %}');
		background-repeat: no-repeat;
		background-size: cover;
		background-position: absolute;
		top: 0px;
		left: 0px;
		right: 0px;
		bottom: 0px;
		margin: auto;
	}
		.form-control, .form-control:focus, .input-group-addon {
		border-color: #e1e1e1;
		border-radius: 0;
	}
	.signup-form {
		width: 390px;
		margin: 0 auto;
		padding: 30px 0;
	}
	.signup-form h2 {
		color: #636363;
		margin: 0 0 15px;
		text-align: center;
	}
	.signup-form .lead {
		font-size: 14px;
		margin-bottom: 30px;
		text-align: center;
	}
	.signup-form form {     
		border-radius: 1px;
		margin-bottom: 15px;
		background: #fff;
		border: 1px solid #f3f3f3;
		box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
		padding: 30px;
	}
	.signup-form .form-group {
		margin-bottom: 20px;
	}
	.signup-form label {
		font-weight: normal;
		font-size: 13px;
	}
	.signup-form .form-control {
		min-height: 38px;
		box-shadow: none !important;
		border-width: 0 0 1px 0;
	}   
	.signup-form .input-group-addon {
		max-width: 42px;
		text-align: center;
		background: none;
		border-bottom: 1px solid #e1e1e1;
		padding-left: 5px;
	}
	.signup-form .btn, .signup-form .btn:active {        
		font-size: 16px;
		font-weight: bold;
		background: #19aa8d !important;
		border-radius: 3px;
		border: none;
		min-width: 140px;
	}
	.signup-form .btn:hover, .signup-form .btn:focus {
		background: #179b81 !important;
	}
	.signup-form a {
		color: #19aa8d;
		text-decoration: none;
	}   
	.signup-form a:hover {
		text-decoration: underline;
	}
	.signup-form .fa {
		font-size: 21px;
		position: relative;
		top: 8px;
	}
	.signup-form .fa-paper-plane {
		font-size: 17px;
	}
	.signup-form .fa-check {
		color: #fff;
		left: 9px;
		top: 18px;
		font-size: 7px;
		position: absolute;
	}
</style>
</head>
<body>
	<div class="signup-form">   
		<form action="{% url 'gameApp:signup' %}" method="post" enctype='multipart/form-data' >
			{% csrf_token %}
			<h2>{{error}}</h2>
			<h2>Create Account</h2>
			<p class="lead">it takes no time</p>
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-user"></i></span>
					<input type="text" class="form-control" name="username" placeholder="Username" required="required">
				</div>
			</div>
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-paper-plane"></i></span>
					<input type="email" class="form-control" name="email" placeholder="Email Address" required="required">
				</div>
			</div>
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-user"></i></span>
					<input type="firstname" class="form-control" name="firstname" placeholder="First Name" required="required">
				</div>
			</div>
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-user"></i></span>
					<input type="lastname" class="form-control" name="lastname" placeholder="Last Name" required="required">
				</div>
			</div>
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-lock"></i></span>
					<input type="text" class="form-control" name="password" placeholder="Password" required="required">
				</div>
			</div>
			<div class="form-group">
				<input type="file" id="myFile" name="filename" required="required">
			</div>        
			<div class="form-group">
				<button type="submit" class="btn btn-primary btn-block btn-lg">Sign Up</button>
			</div>
		</form>
		<div class="text-center">Already have an account? <a href="login">Login here</a>.</div>
	</div>
</body>
</html>